				<div class="box" style="margin-left:10px;">
				  <div class="boxTitle">负责的团队项目</div>
				  <div class="boxMain">

					
					<a href="" class="aTitle"  target="_blank">XiaoD 聊天机器人</a> &nbsp; &nbsp;<br />
					<img src="images/xiaod1.png" /><br />
					说明：XiaoD Services 包括WEBAPP,移动APP <br />
					版本状况：此为CFC发展项目 <br />
					时间：2013年5月21日
					<hr />
					<a href="" class="aTitle"  target="_blank">重庆理工大学数统学院</a> &nbsp; &nbsp;<br />
					
					说明：学院网站<br />
					版本状况：此为CFC商业项目 <br />
					时间：2013年4月19日
					<hr />
					<a href="" class="aTitle"  target="_blank">GGLG Hadoop云计算基础平台</a> &nbsp; &nbsp;<br />
					<img src="images/hadoop-logo.jpg" /><br />
					说明：利用学校废弃主机搭建hadoop云计算基础云平台<br />
					版本状况：已成功运行20个真机节点多日，由于种种原因中间暂停了这个项目，2013年暑假将重新启动这个项目 <br />
					时间：2013年3月17日
					<hr />

					<a href="" class="aTitle"  target="_blank">重庆安福堂</a> &nbsp; &nbsp;<br />
					<img src="images/aft.png" /><br />
					说明：企业网站<br />
					版本状况：此为CFC商业项目 <br />
					时间：2013年1月22日
					<hr />
					<a href="" class="aTitle"  target="_blank">指纹识别签到系统</a> &nbsp; &nbsp;<br />
					说明：指纹签到<br />
					版本状况：现为科研立项重点项目 <br />
					时间：2012年11月30日
					<hr />
					</div>
				</div>		  