				<div class="box" style="margin-left:10px;">
				  <div class="boxTitle">个人项目</div>
				  <div class="boxMain">
					<a href="index.php?controller=diary&art=2&pageID=98" class="aTitle"  target="_blank" title="查看详情">BDPHPunit</a> &nbsp; &nbsp;<a href="https://github.com/BreezeDust/BDPHPunit" target="_blank">点我运行</a><br />
					<img src="img/BDPHP.png" /><br />
					说明：个人网站PHP重写时，产生的副产品，属于个人个性定制产品，WEB UI<br />
					版本状况：V1.0 <br />
					时间：2013年7月22日
					<hr />
					<a href="" class="aTitle"  target="_blank" title="查看详情">BDTomcat</a> &nbsp; &nbsp;<a href="https://github.com/BreezeDust/BDTomcat" target="_blank">点我运行</a><br />
			
					说明：小型HTTP服务器，Serlvet容器，写着玩的<br />
					版本状况：V1.0 <br />
					时间：2013年6月28日
					<hr />
					<a href="index.php?controller=diary&art=2&pageID=97" class="aTitle"  target="_blank" title="查看详情">重庆理工大学首届移动APP大赛官网</a> &nbsp; &nbsp;<a href="http://app.cs.cqut.edu.cn/Default.aspx" target="_blank">点我运行</a><br />
			
					说明：重庆理工大学首届移动APP大赛官网,报名，上传作品，评审后台，WIN8风格设计<br />
					版本状况：目前为第一届比赛 <br />
					时间：2013年4月20日
					<hr />
					<a href="index.php?controller=diary&art=2&pageID=95" class="aTitle"  target="_blank" title="查看详情">JBreeze</a> &nbsp; &nbsp;<a href="http://JBreeze.breezedust.com" target="_blank">点我运行</a><br />
<img src="http://www.breezedust.com/upload/day_130212/201302122104226613.png" style="color: rgb(66, 84, 83); font-family: 'Microsoft YaHei'; font-size: 13px; line-height: normal;" alt=""><br />
					说明：JBreeze是个JavaScript DHTML工具箱，用于RIA程序开发，我的第一个JS框架<br />
					版本状况：托管在GitHUB上,中文官网JBreeze.breezedust.com <br />
					时间：2013年2月12日
					<hr />
					<a href="index.php?controller=diary&art=2&pageID=92" class="aTitle"  target="_blank" title="查看详情">CFC WEB</a> &nbsp; &nbsp;<a href="http://www.CraZyForCode.org" target="_blank">点我运行</a><br />
					<img src="images/CFC_logo_min.png" /><br />
					说明：CFC团队网站，我的第一个单页设计网站<br />
					版本状况：现在由CFC团队维护<br />
					时间：2013年1月13日
					<hr />					
					<a href="index.php?controller=diary&art=2&pageID=90" class="aTitle"  target="_blank" title="查看详情">GGL GROUP (已经上线)</a> &nbsp; &nbsp;<a href="" target="_blank">点我运行</a><br />
					<img src="images/GGLG.png" /><br />
					说明：苟光磊ACM讨论组网站 集成博客系统，ACM题库系统，讨论专区，WebAPP应用平台，开放的API和SDK<br />
					版本状况：现在为V2.0  <br />
					时间：2012年5月5日
					<hr />
					
					<a href="index.php?controller=diary&art=2&pageID=68" class="aTitle"  target="_blank" title="查看详情">Light Blog (暂停开发)</a>&nbsp; &nbsp;<br />
					<img alt="" src="http://www.breezedust.com/pimg/lightblog.png"><br />
					说明：博客系统<br />
					暂停原因：打算用PHP重写<br />
					时间：2011年12月16日<br />
					<hr />
					
					<a href="index.php?controller=diary&art=2&pageID=69" class="aTitle"  target="_blank" title="查看详情">BreezeDust个人站 (已经上线)</a>&nbsp; &nbsp;<a href="http://www.breezedust.com" target="_blank">点我运行</a><br />
					<img src="images/01.png" /><br />
					说明：做给自己的个人网站<br />
					版本状况：现在已经发行V3.0版本<br />
					时间：2011年12月14日
					<hr />
					<a href="index.php?controller=diary&art=2&pageID=67" class="aTitle"  target="_blank" title="查看详情">Web Robot XiaoD (已经上线)</a>
					&nbsp; &nbsp;<a href="http://XiaoD.CrazyForCode.org " target="_blank">点我运行</a><br />
					<img src="images/logob.png" /><br />
					说明：WEB在线聊天机器人,人工智能，中文分析系统<br />
					版本状况：现已经把这个项目放在团队项目里进行维护<br />
					时间：2010年4月9日
					<hr />
					
					<strong>德馨居室WEB管理系统 (已终止)</strong> <br />
					说明：ASP网站系统，集成各项专业企业定制功能，为我的第一个商业项目<br />
					终止原因：源码丢失，无法再对原版本系统进行升级<br />
					时间：2009年6月13日
					<hr />
					
					<strong>PC蛋蛋幸运28统计系统 (已终止)</strong><br />
					说明：VB编写的程序，用于分析HTML元素，自动投分，分析历史数据，预测未来可能出现的号码<br />
					终止原因：不太实用，只针对单独网站，玩那么久，这个软件预测到的，能赚到的钱就30元<br />
					时间：2008年8月21日
					<hr />


					<strong>AI.info (已经下线)</strong><br />
					说明：寄宿于BLOGBUS文件系统的网站，集合人工智能方面消息<br />
					下线原因：已经不符合自我发展<br />
					时间：2008年1月1日  
					</div>
				</div>		  