<div class="box" style="margin-left:10px;">
  <div class="boxTitle">参与的其他项目</div>
  <div class="boxMain" style="height:600px;">
    <a href="https://github.com/Artiano/Artiano" class="aTitle"  target="_blank">Artiano</a> &nbsp; &nbsp;<br />
    <img src="images/artiano.jpg" /><br />
    说明：和开建师兄和小聪一起发起的一个开源机器学习的框架 <br />
    版本状况：现在为内部开发 <br />
    时间：2013年8月23日
    <hr />
  </div>
</div>