				<div class="box" style="margin-left:10px;">
				  <div class="boxTitle">Logo设计</div>
				  <div class="boxMain">
					<strong>Artiano</strong> &nbsp; &nbsp;<br />
					<img src="images/artiano.jpg" /><br />
					说明：和开建师兄和小聪一起发起的一个开源机器学习的框架<br />
					时间：2013年8月23日
					<hr />            
            
					<strong>BDPHPunit</strong> &nbsp; &nbsp;<br />
					<img src="img/BDPHP.png" /><br />
					说明：自己编写的自用PHP单元测试框架 <br />
					时间：2013年7月22日
					<hr />
                    
					<strong>JBreeze</strong> &nbsp; &nbsp;<br />
					<img src="images/JBreeze.png" /><br />
					说明：个人JS框架JBreeze LOGO <br />
					时间：2013年1月13日
					<hr />	
					
					<strong>CrazyForCode.org (CFC)</strong> &nbsp; &nbsp;<br />
					<img src="images/cfc.png" /><br />
					说明：CFC团队 LOGO <br />
					时间：2013年1月13日
					<hr />				  
	
					<strong>重庆芝仪装饰工程有限公司</strong> &nbsp; &nbsp;<br />
					<img src="images/zhiyi.jpg" /><br />
					说明：重庆芝仪装饰工程有限公司 LOGO <br />
					时间：2012年4月14日
					<hr />				  

					<strong>Light Blog</strong> &nbsp; &nbsp;<br />
					<img src="images/lightblog.png" /><br />
					说明：Light Blog LOGO <br />
					时间：2011年12月15日
					<hr />
				  
					<strong>XiaoD Robot</strong> &nbsp; &nbsp;<br />
					<img src="images/logo3.png" /><br />
					说明：XiaoD 聊天机器人的LOGO <br />
					时间：2011年12月14日
					<hr />
					
					<strong>Let's 购</strong> &nbsp; &nbsp;<br />
					<img src="images/logo2.jpg" /><br />
					说明：一个小饰品店的LOGO <br />
					时间：2010年3月1日
					<hr />
					
					<strong>AI.info</strong> &nbsp; &nbsp;<br />
					<img src="images/logo1.jpg" /><br />
					说明：寄宿于BLOGBUS文件系统的全静态网站的LOGO，这个主要用于收集人工智能方面的消息 <br />
					时间：2008年1月1日
					<hr />
					</div>
				</div>		  